https://www.tensorflow.org/tutorials/load_data/pandas_dataframe

In [2]:
import pandas as pd
import tensorflow as tf

In [3]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv')

16384/13273 [=====================================] - 0s 1us/step


In [19]:
df = pd.read_csv(csv_file)

In [20]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [21]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

In [22]:
df['thal'] = pd.Categorical(df['thal'])

In [23]:
df['thal'] = df.thal.cat.codes # thal > text to num

In [24]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   52    1   1       118   186    0        2      190      0      0.0   
299   43    0   4       132   341    1        2      136      1      3.0   
300   65    1   4       135   254    0        2      127      0      2.8   
301   48    1   4       130   256    1        2      150      1      0.0   
302   63    0   4       150   407    0        2      154      0      4.0   

     slope  ca  thal  target  
0        3   0     2       0  
1        2   3     3       1  
2        2   2     4       0  
3        3   0     3       0  
4        1   0     3       0  
..     ...  ..   ...     ...  
298      2   0     2       0  
299      2   0     4       1  
300      2   1     4       1  
301      1   2     4       1  
302      2   3     4       1  

[303 rows x 14 columns]

### tf.data.Dataset 사용하여 데이터로드

In [25]:
target = df.pop('target') # df에서 target이 빠짐
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   52    1   1       118   186    0        2      190      0      0.0   
299   43    0   4       132   341    1        2      136      1      3.0   
300   65    1   4       135   254    0        2      127      0      2.8   
301   48    1   4       130   256    1        2      150      1      0.0   
302   63    0   4       150   407    0        2      154      0      4.0   

     slope  ca  thal  
0        3   0     2  
1        2   3     3  
2        2   2     4  
3        3   0     3  
4        1   0     3  
..     ...  ..   ...  
298      2   0     2  
299      2   0     4  
300      2   1     4  
301      1   2     4  
302      2   3     4  

[303 rows x 13 columns]

In [26]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values)) # (입력, 라벨)

for feat, targ in dataset.take(5):
    print('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


In [28]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

In [29]:
dataset

<TensorSliceDataset shapes: ((13,), ()), types: (tf.float64, tf.int64)>

In [30]:
train_dataset = dataset.shuffle(len(df)).batch(1)
train_dataset

<BatchDataset shapes: ((None, 13), (None,)), types: (tf.float64, tf.int64)>

In [31]:
def get_compiled_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(1)
    ])

    model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
    return model

In [32]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

303/303 [==============================] - 0s 1ms/step - loss: 11.3674 - accuracy: 0.5875ETA: 0s - loss: 14.7101 - accuracy: 0.53
Epoch 2/15
303/303 [==============================] - 0s 1ms/step - loss: 0.8361 - accuracy: 0.7195
Epoch 3/15
303/303 [==============================] - 0s 927us/step - loss: 0.7231 - accuracy: 0.7558
Epoch 4/15
303/303 [==============================] - 0s 762us/step - loss: 0.7572 - accuracy: 0.7195
Epoch 5/15
303/303 [==============================] - 0s 709us/

In [34]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
inputs

{'age': <tf.Tensor 'age_1:0' shape=(None,) dtype=float32>,
 'sex': <tf.Tensor 'sex_1:0' shape=(None,) dtype=float32>,
 'cp': <tf.Tensor 'cp_1:0' shape=(None,) dtype=float32>,
 'trestbps': <tf.Tensor 'trestbps_1:0' shape=(None,) dtype=float32>,
 'chol': <tf.Tensor 'chol_1:0' shape=(None,) dtype=float32>,
 'fbs': <tf.Tensor 'fbs_1:0' shape=(None,) dtype=float32>,
 'restecg': <tf.Tensor 'restecg_1:0' shape=(None,) dtype=float32>,
 'thalach': <tf.Tensor 'thalach_1:0' shape=(None,) dtype=float32>,
 'exang': <tf.Tensor 'exang_1:0' shape=(None,) dtype=float32>,
 'oldpeak': <tf.Tensor 'oldpeak_1:0' shape=(None,) dtype=float32>,
 'slope': <tf.Tensor 'slope_1:0' shape=(None,) dtype=float32>,
 'ca': <tf.Tensor 'ca_1:0' shape=(None,) dtype=float32>,
 'thal': <tf.Tensor 'thal_1:0' shape=(None,) dtype=float32>}

In [54]:
x = tf.stack(list(inputs.values()), axis=-1) # axis = -1 가장 낮은 차원 뒤쪽
x = tf.keras.layers.Dense(10, activation='relu')(x)
x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

In [55]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)
for dict_slice in dict_slices.take(1): # 열 정보를 남긴다. 어떤 열이었는지
    print(dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [56]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 0s 1ms/step - loss: 2.2723 - accuracy: 0.5776
Epoch 2/15
19/19 [==============================] - 0s 1ms/step - loss: 1.3725 - accuracy: 0.6172
Epoch 3/15
19/19 [==============================] - 0s 1ms/step - loss: 0.8653 - accuracy: 0.6667
Epoch 4/15
19/19 [==============================] - 0s 1ms/step - loss: 0.6916 - accuracy: 0.7063
Epoch 5/15
19/19 [==============================] - 0s 1ms/step - loss: 0.6209 - accuracy: 0.7129
Epoch 6/15
19/19 [==============================] - 0s 2ms/step - loss: 0.5856 - accuracy: 0.7195
Epoch 7/15
19/19 [==============================] - 0s 1ms/step - loss: 0.5671 - accuracy: 0.7228
Epoch 8/15
19/19 [==============================] - 0s 2ms/step - loss: 0.5561 - accuracy: 0.7195
Epoch 9/15
19/19 [==============================] - 0s 1ms/step - loss: 0.5484 - accuracy: 0.7195
Epoch 10/15
19/19 [==============================] - 0s 1ms/step - loss: 0.5426 - accuracy: 0.7228
Epoch 11/15
19/19 [